import { FormEvent, useState } from 'react';
import { Bot, Database, Send, Sparkles, UserRound } from 'lucide-react';
import { apiClient } from '../../api/client';

type ChatMessage = { id: number; role: 'user' | 'assistant'; text: string; provider?: string };
const examples = ['What should I reorder today?', 'How much profit did I make this month?', 'Which customer spends the most?', 'How much money is blocked in inventory?', 'Give me a business health summary.'];

export const AssistantPanel = () => {
  const [question, setQuestion] = useState('');
  const [messages, setMessages] = useState<ChatMessage[]>([{ id: 1, role: 'assistant', text: 'I can analyze your live showroom database. Ask about profit, stock, customer value, pending payments, or buying decisions.', provider: 'Gemini with local fallback' }]);
  const [busy, setBusy] = useState(false);
  const ask = async (event?: FormEvent, suggested?: string) => {
    event?.preventDefault(); const prompt = (suggested ?? question).trim(); if (!prompt || busy) return;
    setMessages((current) => [...current, { id: Date.now(), role: 'user', text: prompt }]); setQuestion(''); setBusy(true);
    try { const response = await apiClient.askAI(prompt); setMessages((current) => [...current, { id: Date.now() + 1, role: 'assistant', text: response.answer, provider: response.provider }]); }
    catch (error) { setMessages((current) => [...current, { id: Date.now() + 1, role: 'assistant', text: error instanceof Error ? error.message : 'AI request failed', provider: 'Error' }]); }
    finally { setBusy(false); }
  };
  return <div className="grid min-h-[calc(100vh-7rem)] gap-5 pb-20 lg:grid-cols-[280px_minmax(0,1fr)] lg:pb-0">
    <aside className="panel self-start"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-md bg-cyan-50 text-cyan-700"><Sparkles size={19} /></span><div><p className="font-black">Gemini Copilot</p><p className="text-xs text-slate-500">Live business context</p></div></div><div className="mt-6 border-t border-slate-100 pt-5"><p className="text-xs font-bold uppercase text-slate-500">Suggested analysis</p><div className="mt-3 grid gap-2">{examples.map((example) => <button key={example} className="rounded-md border border-slate-200 p-3 text-left text-sm font-semibold leading-5 text-slate-700 hover:border-cyan-300 hover:bg-cyan-50" onClick={() => ask(undefined, example)}>{example}</button>)}</div></div><div className="mt-6 rounded-md bg-slate-950 p-3 text-white"><p className="flex items-center gap-2 text-xs font-bold"><Database size={14} className="text-cyan-400" /> Database grounded</p><p className="mt-2 text-xs leading-5 text-slate-400">Answers receive current sales, inventory, customer, and expense context. Gemini is used first; deterministic analytics remains available if Google is unavailable.</p></div></aside>
    <section className="panel flex min-h-[650px] flex-col p-0 md:p-0"><header className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h1 className="font-black">Business AI conversation</h1><p className="text-xs text-slate-500">Private to your authenticated workspace</p></div><span className="status-pill bg-emerald-50 text-emerald-700"><span className="size-2 rounded-full bg-emerald-500" /> Online</span></header><div className="flex-1 space-y-5 overflow-y-auto p-5">{messages.map((message) => <div key={message.id} className={`flex gap-3 ${message.role === 'user' ? 'justify-end' : ''}`}>{message.role === 'assistant' ? <span className="grid size-9 shrink-0 place-items-center rounded-md bg-slate-950 text-cyan-400"><Bot size={17} /></span> : null}<div className={`max-w-2xl rounded-lg px-4 py-3 text-sm leading-6 ${message.role === 'user' ? 'bg-cyan-600 text-white' : 'border border-slate-200 bg-slate-50 text-slate-800'}`}><p>{message.text}</p>{message.provider ? <p className={`mt-2 text-[11px] font-bold ${message.role === 'user' ? 'text-cyan-100' : 'text-slate-400'}`}>Provider: {message.provider}</p> : null}</div>{message.role === 'user' ? <span className="grid size-9 shrink-0 place-items-center rounded-md bg-cyan-100 text-cyan-800"><UserRound size={17} /></span> : null}</div>)}{busy ? <div className="flex gap-3"><span className="grid size-9 place-items-center rounded-md bg-slate-950 text-cyan-400"><Bot size={17} /></span><div className="rounded-lg bg-slate-100 px-4 py-3 text-sm font-semibold text-slate-500">Analyzing live showroom data...</div></div> : null}</div><form className="no-print border-t border-slate-200 p-4" onSubmit={(event) => ask(event)}><div className="flex gap-2"><textarea className="field min-h-12 flex-1 resize-none" rows={1} value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); ask(); } }} placeholder="Ask a question about your showroom..." /><button className="btn-primary size-12 px-0" disabled={busy || !question.trim()} title="Send question"><Send size={18} /></button></div></form></section>
  </div>;
};
